global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: wallet-ledger-service
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials: local-metrics-token
    static_configs:
      - targets: ["wallet-ledger-service:8080"]

  - job_name: api-gateway-service
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials: local-metrics-token
    static_configs:
      - targets: ["api-gateway-service:8080"]

  - job_name: ops-risk-service
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials: local-metrics-token
    static_configs:
      - targets: ["ops-risk-service:8080"]

  - job_name: audit-export-worker
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials: local-metrics-token
    static_configs:
      - targets: ["audit-export-worker:8080"]
